name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm install

      - name: Start the server
        run: npm start

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist