name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
      TEST_M: ${{ secrets.TEST_M }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm install

      - name: Log MongoDB URI
        run: "echo 'MongoDB URI: $MONGO_DB_URI'"

      - name: Log TEST_M
        run: "echo 'TEST_M: $TEST_M'"

      - name: Start the server
        run: npm start

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist